'use client'

import { useState } from 'react'
import { ArrowRight, CheckCircle2, Heart, Menu, Phone, ShieldCheck, Users, X } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo%201-cJ46PUnpDa3Bp87kTxPuac9gaE0ni2.png'
const images = {
  hero: 'https://images.pexels.com/photos/17844227/pexels-photo-17844227.jpeg?cs=srgb&fm=jpg&w=1600',
  mission: 'https://images.pexels.com/photos/5196013/pexels-photo-5196013.jpeg?cs=srgb&fm=jpg&w=1200',
  children: 'https://images.pexels.com/photos/28593055/pexels-photo-28593055.jpeg?cs=srgb&fm=jpg&w=1200',
  healthcare: 'https://images.pexels.com/photos/37285156/pexels-photo-37285156.jpeg?cs=srgb&fm=jpg&w=1200',
  community: 'https://images.pexels.com/photos/35797398/pexels-photo-35797398.jpeg?cs=srgb&fm=jpg&w=1200',
  water: 'https://images.pexels.com/photos/28101458/pexels-photo-28101458.jpeg?cs=srgb&fm=jpg&w=1200',
  food: 'https://images.pexels.com/photos/6995201/pexels-photo-6995201.jpeg?cs=srgb&fm=jpg&w=1200',
  training: 'https://images.pexels.com/photos/25406007/pexels-photo-25406007.jpeg?cs=srgb&fm=jpg&w=1200',
}

const copy = {
  en: { home: 'Home', about: 'About Us', causes: 'Our Causes', projects: 'Projects', events: 'Our Activities', volunteer: 'Volunteer', contact: 'Contact', donate: 'Donate Now', heroTag: 'Together we can', heroTitle: 'Build a better tomorrow', heroBody: 'We work for the development and better future of underprivileged children and communities.', mission: 'Our mission', missionTitle: 'Every child deserves a better future', missionBody: 'We empower communities through education, healthcare, nutrition, and sustainable support.', causesTitle: 'Our causes', causesBody: 'Practical programs that turn compassion into lasting opportunity.', projectsTitle: 'Projects that create real change', volunteerTitle: 'Become a volunteer', volunteerBody: 'Join dedicated people helping us make a bigger impact.', stories: 'Stories of hope and change', name: 'Full name', email: 'Email address', submit: 'Submit application', eventsTag: 'Our activities', eventsTitle: 'Recent activities making an impact', eventsBody: 'A look at our latest programs and outreach across Burundi.', viewAllEvents: 'View all activities', activities: [
    { image: images.healthcare, place: 'Bujumbura', date: 'Sep 12 · 9:00 AM', title: 'Health camp for children', body: 'Free checkups, vaccinations and nutrition screening for children under five.' },
    { image: images.children, place: 'Gitega', date: 'Sep 20 · 10:00 AM', title: 'Back-to-school kits & education drive', body: 'Distributing books, uniforms and school supplies to underprivileged students.' },
    { image: images.water, place: 'Ngozi', date: 'Sep 28 · 8:00 AM', title: 'Clean water access project', body: "Restoring safe water points so families no longer walk hours for water." },
    { image: images.food, place: 'Bujumbura', date: 'Oct 14 · 11:00 AM', title: 'Food & nutrition distribution', body: 'Monthly food packages for vulnerable households facing food insecurity.' },
    { image: images.training, place: 'Gitega', date: 'Oct 22 · 9:00 AM', title: "Women's vocational training", body: 'Teaching tailoring skills so mothers can build a sustainable income.' },
    { image: images.community, place: 'Kayanza', date: 'Oct 5 · 8:00 AM', title: 'Community water point rehabilitation', body: 'Meeting families to plan and repair wells and boreholes together.' },
    { image: images.hero, place: 'Muyinga', date: 'Oct 30 · 9:00 AM', title: 'Community outreach & family support day', body: 'Meeting families to assess needs and connect them with our programs.' },
    { image: images.mission, place: 'Bujumbura', date: 'Nov 8 · 10:00 AM', title: 'Volunteer mentorship day', body: 'Volunteers spend the day mentoring children and supporting local families.' },
  ] },
  fr: { home: 'Accueil', about: 'À propos', causes: 'Nos causes', projects: 'Projets', events: 'Nos Activite', volunteer: 'Bénévolat', contact: 'Contact', donate: 'Faire un don', heroTag: 'Ensemble, nous pouvons', heroTitle: 'Construisons un avenir meilleur', heroBody: 'Nous œuvrons pour l’avenir des enfants et des communautés défavorisés.', mission: 'Notre mission', missionTitle: 'Chaque enfant mérite un avenir meilleur', missionBody: 'Nous accompagnons les communautés grâce à l’éducation, la santé, la nutrition et un soutien durable.', causesTitle: 'Nos causes', causesBody: 'Des programmes concrets qui transforment la solidarité en opportunités durables.', projectsTitle: 'Des projets qui changent des vies', volunteerTitle: 'Devenez bénévole', volunteerBody: 'Rejoignez une équipe engagée pour amplifier notre impact.', stories: 'Histoires d’espoir et de changement', name: 'Nom complet', email: 'Adresse e-mail', submit: 'Envoyer ma candidature', eventsTag: 'Nos activités', eventsTitle: 'Activités récentes qui changent des vies', eventsBody: 'Un aperçu de nos derniers programmes et actions de terrain au Burundi.', viewAllEvents: 'Voir toutes les activités', activities: [
    { image: images.healthcare, place: 'Bujumbura', date: '12 sept. · 09h00', title: 'Camp de santé pour les enfants', body: 'Consultations gratuites, vaccination et dépistage nutritionnel pour les moins de cinq ans.' },
    { image: images.children, place: 'Gitega', date: '20 sept. · 10h00', title: 'Rentrée scolaire et distribution de kits', body: 'Distribution de cahiers, uniformes et fournitures aux élèves défavorisés.' },
    { image: images.water, place: 'Ngozi', date: '28 sept. · 08h00', title: "Accès à l'eau potable", body: "Réhabilitation de points d'eau pour éviter des heures de marche aux familles." },
    { image: images.food, place: 'Bujumbura', date: '14 oct. · 11h00', title: 'Distribution alimentaire et nutritionnelle', body: 'Colis alimentaires mensuels pour les ménages vulnérables.' },
    { image: images.training, place: 'Gitega', date: '22 oct. · 09h00', title: 'Formation en couture pour les femmes', body: 'Apprentissage de la couture pour permettre aux mères de générer un revenu durable.' },
    { image: images.community, place: 'Kayanza', date: '05 oct. · 08h00', title: "Réhabilitation d'un point d'eau communautaire", body: "Rencontre avec les familles pour planifier et réparer puits et forages." },
    { image: images.hero, place: 'Muyinga', date: '30 oct. · 09h00', title: 'Journée de proximité communautaire', body: 'Rencontre des familles pour évaluer leurs besoins et les orienter vers nos programmes.' },
    { image: images.mission, place: 'Bujumbura', date: '08 nov. · 10h00', title: 'Journée de mentorat des bénévoles', body: 'Nos bénévoles accompagnent les enfants et soutiennent les familles locales.' },
  ] },
  rn: { home: 'Ahabanza', about: 'Ivyerekeye twebwe', causes: 'Imigambi yacu', projects: 'Imishinga', events: 'Ibikorwa', volunteer: 'Abakorerabushake', contact: 'Twandikire', donate: 'Tanga intererano', heroTag: 'Hamwe turashoboye', heroTitle: 'Twubake ejo heza', heroBody: 'Dukorera iterambere ry’abana n’imiryango itishoboye.', mission: 'Intumbero yacu', missionTitle: 'Umwana wese akwiye kazoza keza', missionBody: 'Dufasha imiryango biciye mu burezi, amagara meza, imirire n’iterambere rirama.', causesTitle: 'Imigambi yacu', causesBody: 'Imigambi ifatika ihindura ubuntu amahirwe arama.', projectsTitle: 'Imishinga ihindura ubuzima', volunteerTitle: 'Ba umukorerabushake', volunteerBody: 'Injira mu mugwi w’abantu bitanga kugira dufashe benshi.', stories: 'Inkuru z’icizere n’impinduka', name: 'Amazina yose', email: 'Imeyili', submit: 'Rungika ubusabe', eventsTag: 'Ibikorwa vyacu', eventsTitle: 'Ibikorwa vya vuba bihindura ubuzima', eventsBody: 'Raba ibikorwa vyacu vya vuba mu Burundi.', viewAllEvents: 'Raba ibikorwa vyose', activities: [
    { image: images.healthcare, place: 'Bujumbura', date: '12/9 · 09h00', title: "Ikambu ryo kuraba amagara y'abana", body: "Kuraba ubuzima ku buntu, gukingira no kuraba imirire y'abana bari munsi y'imyaka itanu." },
    { image: images.children, place: 'Gitega', date: '20/9 · 10h00', title: 'Gutanga ibikoresho vyo kwiga', body: "Gutanga impapuro, imyambaro n'ibikoresho vy'ishure ku bana batishoboye." },
    { image: images.water, place: 'Ngozi', date: '28/9 · 08h00', title: 'Kuronka amazi meza', body: "Gusubiramwo utuntu tw'amazi kugira imiryango ntibagende amasaha bahiga amazi." },
    { image: images.food, place: 'Bujumbura', date: '14/10 · 11h00', title: 'Gutanga ivyokurya n’imirire', body: 'Gutanga impfungurwa ku miryango igoyagoye buri kwezi.' },
    { image: images.training, place: 'Gitega', date: '22/10 · 09h00', title: 'Kwigisha ukudoda ku bagore', body: 'Kwigisha ukudoda kugira ababyeyi baronke inyungu zirama.' },
    { image: images.community, place: 'Kayanza', date: '5/10 · 08h00', title: "Gusana iciriba c'abaturage", body: "Guhura n'imiryango kugira duteguriranye no gusana ibiriba n'amariba." },
    { image: images.hero, place: 'Muyinga', date: '30/10 · 09h00', title: 'Umusi wo kwitura imiryango', body: 'Kubonana n’imiryango kugira turabe ivyipfuzo vyabo tubafashe.' },
    { image: images.mission, place: 'Bujumbura', date: '8/11 · 10h00', title: "Umusi w'abakorerabushake bo kuraba abana", body: 'Abakorerabushake baraba abana kandi bagafasha imiryango bo mu karere.' },
  ] },
}

const whatsapp = 'https://wa.me/25769467870'

export default function Page() {
  const [lang, setLang] = useState<keyof typeof copy>('fr')
  const [open, setOpen] = useState(false)
  const [showAllEvents, setShowAllEvents] = useState(false)
  const t = copy[lang]
  const nav = [[t.home, '#home'], [t.about, '#about'], [t.causes, '#causes'], [t.projects, '#projects'], [t.events, '#events'], [t.volunteer, '#volunteer'], [t.contact, '#contact']]

  return <main className="min-h-screen bg-background text-foreground">
    <div className="topbar"><div className="container flex items-center justify-between"><span>HopeNest Impact · Together we can make a difference</span><a href={whatsapp}>WhatsApp: +257 69 46 78 70</a></div></div>
    <header className="site-header"><div className="container header-inner"><a href="#home" className="logo-link"><img src={logo} alt="HopeNest Impact" /></a><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button><nav className={open ? 'nav open' : 'nav'}>{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}<select value={lang} onChange={(e) => setLang(e.target.value as keyof typeof copy)} aria-label="Language"><option value="en">EN</option><option value="fr">FR</option><option value="rn">RN</option></select><a className="button small" href="#donate">{t.donate}</a></nav></div></header>

    <section id="home" className="hero"><div className="hero-image" style={{ backgroundImage: `url(${images.hero})` }} /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow">{t.heroTag}</p><h1>{t.heroTitle}</h1><p className="hero-copy">{t.heroBody}</p><div className="actions"><a className="button" href="#donate">{t.donate} <Heart size={17} fill="currentColor" /></a><a className="button outline" href="#about">{t.about} <ArrowRight size={17} /></a></div></div></section>
    <section className="stats"><div className="container stats-grid"><div><strong>25,000+</strong><span>Children reached</span></div><div><strong>15,500+</strong><span>Meals provided</span></div><div><strong>340+</strong><span>Communities impacted</span></div><div><strong>120+</strong><span>Active volunteers</span></div></div></section>

    <section id="about" className="section"><div className="container split"><div className="image-card"><img src={images.mission} alt="Community support and medical care" /></div><div><p className="eyebrow blue">{t.mission}</p><h2>{t.missionTitle}</h2><p>{t.missionBody}</p><ul className="check-list"><li><CheckCircle2 /> Quality education for every child</li><li><CheckCircle2 /> Healthcare and nutrition support</li><li><CheckCircle2 /> Community development programs</li></ul><a className="text-link" href="#projects">Discover our work <ArrowRight size={17} /></a></div></div></section>

    <section id="causes" className="section soft"><div className="container"><p className="eyebrow blue">{t.causes}</p><h2>{t.causesTitle}</h2><p className="section-intro">{t.causesBody}</p><div className="cause-grid"><article><div className="cause-icon"><Heart /></div><h3>Education for all</h3><p>Learning materials, mentoring and safe spaces for children.</p></article><article><div className="cause-icon"><ShieldCheck /></div><h3>Health & nutrition</h3><p>Medical support and healthy meals for families in need.</p></article><article><div className="cause-icon"><Users /></div><h3>Community care</h3><p>Local initiatives that create resilience and opportunity.</p></article></div></div></section>

    <section id="donate" className="impact"><div className="container impact-grid"><div><p className="eyebrow">Make an impact</p><h2>Your donation can change lives</h2><p>Every contribution helps bring hope and create lasting change in communities.</p><a className="button light" href={whatsapp}>Donate via WhatsApp <Heart size={17} fill="currentColor" /></a></div><div className="donation-card"><span>Choose an amount</span><div className="amounts"><button>$10</button><button>$25</button><button>$50</button><button>$100</button></div><a href={whatsapp} className="text-link light-text">I want to help <ArrowRight size={17} /></a></div></div></section>

    <section id="projects" className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow blue">Our work</p><h2>{t.projectsTitle}</h2></div></div><div className="project-grid"><article className="project"><img src={images.children} alt="Children learning together" /><div><h3>Education for all</h3><p>Quality education and learning materials for children.</p><a href="#contact">Learn more <ArrowRight size={15} /></a></div></article><article className="project"><img src={images.healthcare} alt="Health support for a community" /><div><h3>Healthcare support</h3><p>Free healthcare camps and medical support for families.</p><a href="#contact">Learn more <ArrowRight size={15} /></a></div></article><article className="project"><img src={images.community} alt="HopeNest community project" /><div><h3>Community development</h3><p>Building stronger communities through local action.</p><a href="#contact">Learn more <ArrowRight size={15} /></a></div></article></div></div></section>

    <section id="events" className="events-band"><div className="container"><div className="section-heading"><div><p className="eyebrow blue">{t.eventsTag}</p><h2>{t.eventsTitle}</h2><p className="section-intro">{t.eventsBody}</p></div></div><div className="project-grid activity-grid">{(showAllEvents ? t.activities : t.activities.slice(0, 5)).map((a, i) => <article key={i} className="project"><img src={a.image} alt={a.title} /><div><span className="activity-meta">{a.place} · {a.date}</span><h3>{a.title}</h3><p>{a.body}</p></div></article>)}</div>{!showAllEvents && t.activities.length > 5 && <div className="activity-more"><button className="text-link" onClick={() => setShowAllEvents(true)}>{t.viewAllEvents} <ArrowRight size={17} /></button></div>}</div></section>

    <section id="volunteer" className="section"><div className="container volunteer"><div><p className="eyebrow blue">Join our mission</p><h2>{t.volunteerTitle}</h2><p>{t.volunteerBody}</p><div className="feature"><Users /><span>Make a direct difference in your community</span></div><div className="feature"><ShieldCheck /><span>Be part of a trusted, transparent foundation</span></div></div><form onSubmit={(e) => e.preventDefault()}><input placeholder={t.name} required /><input type="email" placeholder={t.email} required /><input placeholder="Phone number" /><select><option>Select role</option><option>Education</option><option>Healthcare</option><option>Community outreach</option></select><button className="button" type="submit">{t.submit} <ArrowRight size={17} /></button></form></div></section>

    <section className="stories"><div className="container"><p className="eyebrow blue">{t.stories}</p><div className="quotes"><blockquote>“HopeNest gave my children a chance to learn and dream again.”<strong>— Amina, parent</strong></blockquote><blockquote>“Volunteering here has been the most rewarding experience of my life.”<strong>— David, volunteer</strong></blockquote><blockquote>“Small acts of kindness are creating real change.”<strong>— Grace, supporter</strong></blockquote></div></div></section>
    <footer id="contact"><div className="container footer-top"><div><a className="logo-link footer-logo" href="#home"><img src={logo} alt="HopeNest Impact" /></a><p>Creating a better world for children and communities in need.</p></div><div><h3>Quick links</h3><a href="#about">{t.about}</a><a href="#causes">{t.causes}</a><a href="#projects">{t.projects}</a><a href="#events">{t.events}</a></div><div><h3>Contact</h3><a href="tel:+25769467870"><Phone size={15} /> +257 69 46 78 70</a><a href={whatsapp}>WhatsApp us</a><a href="mailto:hello@hopenest.org">hello@hopenest.org</a></div><div><h3>Stay connected</h3><p>Follow our work and help us share hope.</p><a className="button small" href={whatsapp}>Contact us</a></div></div><div className="container copyright">© 2026 HopeNest Impact. Together we can make a difference.</div></footer>
  </main>
}
